name: ever
on:
  pull_request:
  push:
    branches:
    - main
jobs:
  ever:
    runs-on: ubuntu-latest
    steps:
    - run: echo hola
    - if: github.event_name == 'merge_group'
      run: |
        echo ${{ github.event.merge_group.head_ref }}
        echo ${{ github.event.merge_group.base_ref }}
        
